### ISSUE TITLE
Support for Gatsby v3

### ISSUE THREAD

**Issue by t2ca** [gatsbyjs/themes#106]
I was wondering if there are any plans to update gatsby-theme-blog?

**Comment by theowenyoung** [comment]
Same here. Waiting.

**Comment by LekoArts** [comment]
I'm in the process of upgrading everything!
https://github.com/gatsbyjs/themes/pull/112

**Comment by LekoArts** [comment]
Published canary version to try out:

```
 - gatsby-theme-blog-core@gatsby-v3
 - gatsby-theme-blog-darkmode@gatsby-v3
 - gatsby-theme-blog@gatsby-v3
 - gatsby-theme-i18n-lingui@gatsby-v3
 - gatsby-theme-i18n-react-i18next@gatsby-v3
 - gatsby-theme-i18n-react-intl@gatsby-v3
 - gatsby-theme-i18n@gatsby-v3
 - gatsby-theme-notes@gatsby-v3
 - gatsby-theme-ui-preset@gatsby-v3
```

**Comment by t2ca** [comment]
Thanks, it's working fine here.

**Comment by OdysLam** [comment]
Hey, I tried installing it but I get `No matching version found for gatsby-theme-blog-core@3.0.0.` 

I used `npm install gatsby-theme-blog@gatsby-v3`

**Comment by LekoArts** [comment]
Yeah, somehow Lerna messed up the versioning of this: https://unpkg.com/browse/gatsby-theme-blog@2.1.1-gatsby-v3.14/package.json

I'll publish all blog/blog-core/notes/theme-ui-preset again

**Comment by OdysLam** [comment]
Thanks! As I just started learning Gatsby (and react for that matter), I have set up a skeleton for my website. How the theme will help me? predefined graphql queries and the like?

**Comment by LekoArts** [comment]
Installing `gatsby-theme-blog@gatsby-v3` should work now :)

> How the theme will help me? predefined graphql queries and the like?

Themes can be understood as pre-packaged Gatsby sites so they can include `gatsby-config.js`, `gatsby-node.js` etc. and in this instance the blog theme has predefined GraphQL queries and styling on top of it. You can read more here: https://www.gatsbyjs.com/docs/themes/

**Comment by LekoArts** [comment]
```
Successfully published:
 - gatsby-theme-blog-core@3.0.0
 - gatsby-theme-blog-darkmode@3.0.0
 - gatsby-theme-blog@3.0.0
 - gatsby-theme-i18n-lingui@2.0.0
 - gatsby-theme-i18n-react-i18next@2.0.0
 - gatsby-theme-i18n-react-intl@2.0.0
 - gatsby-theme-i18n@2.0.0
 - gatsby-theme-notes@3.0.0
 - gatsby-theme-ui-preset@2.0.0
```
