### ISSUE TITLE
is there a way to create subscribe section in gatsby-blog-theme

### ISSUE THREAD

**Issue by eminvergil** [gatsbyjs/themes#57]
i am trying to build a blog site for myself.i love this theme but it doesnt allow to edit , change the layout because when you download it comes as package,so how can i create subscribe section ? or change layout , add different sections ?

**Comment by gh640** [comment]
You can use the "shadowing" function to override components provided by the theme. The following page helps:

- [Shadowing in Gatsby Themes | GatsbyJS](https://www.gatsbyjs.org/docs/themes/shadowing/)
