### ISSUE TITLE
Inline image for post

### ISSUE THREAD

**Issue by mdovn** [gatsbyjs/themes#58]
Inside my `mdx` post, how can I add an inline image? 
I've tried to place an image named `foo.png` inside the post folder and then insert this markdown:
```mdx
![test](./foo.png)
```
but it doesn't work

**Comment by varunbhaya03** [comment]
@mdovn I am not able to reproduce this issue, able to render `.png` as well as `.jpeg` extension images inside `mdx` file. 
Can you provide the error and code snippet here?

**Comment by laurieontech** [comment]
I'm going to close this since we don't have the ability to reproduce the issue. Please feel free to reopen it if you have an example for us to dig into.
