### ISSUE TITLE
Integration of gatsby-theme-blog and i18n

### ISSUE THREAD

**Issue by ColadaFF** [gatsbyjs/themes#62]
Hi there,

I've been trying to integrate i18n with the new gatsby-theme-blog, but haven't been able to do so.

I've tried a lot of gatsby i18n packages.

Is there and official way to do this?

I also tried with gatsby-theme-i18n

But get the error "Cannot query field "themeI18N" on type "Query"."

Thanks!

**Comment by alexislepresle** [comment]
Hello @ColadaFF ,

Did you use `gatsby-plugin-mdx`? 
I will soon create a blog theme with i18n.
