### ISSUE TITLE
Blank or 404 page for urls prefixed with default locale

### ISSUE THREAD

**Issue by will-weiss** [gatsbyjs/themes#63]
Hello! Is there a way of augmenting the configuration for a project set up identically to the [example-react-intl](https://github.com/gatsbyjs/themes/tree/master/starters/example-react-intl) project so that pages prefixed with the 2 letter code for the default locale are rendered or redirected? That is, in that project if I access `localhost:8000/en` I would expect a page just like `localhost:8000` to load or to be redirected there. Is there a way to get that behavior?

Thanks in advance!

**Comment by philschonholzer** [comment]
Got the same problem. Nothing is being rendered with the default language in the url.

**Comment by LekoArts** [comment]
Closed in favor of umbrella issue :)
https://github.com/gatsbyjs/themes/issues/43#issuecomment-692632145
