### ISSUE TITLE
How to use navigate from gatsby with i18n?

### ISSUE THREAD

**Issue by philschonholzer** [gatsbyjs/themes#66]
If the default locale would also be prefixed using navigate from gatsby would be easy:

```js
navigate(`/${locale}/page-3`)
```

But because the default is not prefixed:

```js
navigate(`/${locale === defaultLang ? `` : `${locale}/`}page-3`)
```

Is there a better way? Can you maybe provide a helper for this?

**Comment by LekoArts** [comment]
Will close this in favor of https://github.com/gatsbyjs/themes/issues/43 :)
