### ISSUE TITLE
[gatsby-theme-i18n] Can page be translated?

### ISSUE THREAD

**Issue by mi5ha** [gatsbyjs/themes#79]
Hi there,

I tried creating index.de.tsx page, and plugin generates /de/ page. But that page still shows index.tsx page!

Is this theme meant to be used this way?
Thanx

**Comment by flogy** [comment]
Have the same issue. It seems to me that only MDX files are checked for a `.de.` pattern and all others are not?

**Comment by eneax** [comment]
@mi5ha I had the same problem, and solved it by adding the `locale` to the query as shown in the [example-18n](https://github.com/gatsbyjs/themes/blob/6ff5c7ae256a732f790401512f8a86e09e11b070/starters/example-i18n/src/templates/blog-template.js#L28)

```
export const query = graphql`
  query($locale: String!, $slug: String!) {
    mdx(
      fields: { locale: { eq: $locale } }
      frontmatter: { slug: { eq: $slug } }
    ) {
      frontmatter {
        slug
        title
      }
      body
    }
  }
`
```

I hope it helps!
