### ISSUE TITLE
Link to github source for gatsby-theme-blog is broken

### ISSUE THREAD

**Issue by finjo-the-great** [gatsbyjs/themes#88]
If I click the "View plugin on github" link on the [gatsby-theme-blog page](https://www.gatsbyjs.com/plugins/gatsby-theme-blog/), it goes to a [URL that gives a 404](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-theme-blog).

**Comment by laurieontech** [comment]
Thanks for the PR! The code for that is in another repo and they're aware of the issue. I'm going to close this as a result.
