### ISSUE TITLE
[gatsby-theme-blog-core] Can I custom the default limit 1000?

### ISSUE THREAD

**Issue by theowenyoung** [gatsbyjs/themes#94]
https://github.com/gatsbyjs/themes/blob/fead1c23870cf37e8ce1a5476a43ef580ca1d509/packages/gatsby-theme-blog-core/gatsby-node.js#L259-L272

Hi, Can I change the limit `1000`?

**Comment by laurieontech** [comment]
Right now that is not a configurable field. So unfortunately you cannot.

If you'd like to submit a PR to make it so, we'd be open to that.
